//Container Components:
//Purpose: How things work (data fetching, state updates)
//Aware of Redux: Yes
//To read data: Subscribe to Redux state
//To change data: Dispatch Redux actions
//Are written: Usually generated by React Redux
import React from "react";
import { connect } from "react-redux";
import { insertHero } from "../actions";

const AddHero = ({ dispatch }) => {
  let input;
  return (
    <div>
      <form
        onSubmit={e => {
          e.preventDefault();
          if (!input.value.trim()) {
            return;
          }
          dispatch(insertHero(input.value));
          input.value = "";
        }}
      >
        <input ref={node => (input = node)} />
        <button type="submit">Add Hero</button>
      </form>
    </div>
  );
};

export default connect()(AddHero);
