//Container Components:
//Purpose: How things work (data fetching, state updates)
//Aware of Redux: Yes
//To read data: Subscribe to Redux state
//To change data: Dispatch Redux actions
//Are written: Usually generated by React Redux
import HerosList from "../components/HerosList";
import { connect } from "react-redux";

const mapStateToProps = ({ heros }) => {
  return {
    heros: heros
  };
};

const mapDispatchToProps = dispatch => ({
  //toggleHeros: movie => dispatch(toggleHeros(movie))
});

export default connect(
  mapStateToProps,
  mapDispatchToProps
)(HerosList);
