//Container Components:
//Purpose: How things work (data fetching, state updates)
//Aware of Redux: Yes
//To read data: Subscribe to Redux state
//To change data: Dispatch Redux actions
//Are written: Usually generated by React Redux
import deleteHero from "../actions";
import HerosList from "../components/HerosList";
import { connect } from "react-redux";

const mapStateToProps = myDatabaseState => {
  return {
    heros: myDatabaseState.heros
  };
};

export default connect(mapStateToProps)(HerosList);
